public enum ClientPacketId
{
    None = 0,
    CreateAccount,
    DeleteAccount,
    Login,
    Logout,
    GameClose,
    RequestCharacterList,
    CreateCharacter,
    DeleteCharacter,
    SelectCharacter,
    RequestCharacterStatus,
    RequestRoomList,
    SkillUp,
    EquipUpgrade,
    CreateRoom,
    EnterRoom,
    RequestRoomUserData,
    ExitRoom,
    StartGame,
    RequestUdpConnection,
    RequestMonsterSpawnList,
    RequestDungeonData,
    UdpConnectComplete,
}

public enum ServerPacketId
{
    None = 0,
    CreateAccountResult,
    DeleteAccountResult,
    LoginResult,
    LogoutResult,
    CharacterList,
    CreateCharacterResult,
    DeleteChracterResult,
    RoomList,
    CharacterStatus,
    SkillUpResult,
    EquipUpgradeResult,
    CreateRoomResult,
    EnterRoomResult,
    RoomUserData,
    ExitRoomResult,
    StartGame,
    SpawnMonsterList,
    DungeonData,
    UdpConnection,
    StartDungeon,
}

public enum P2PPacketId
{
    None = 0,
    RequestConnectionCheck,
    ConnectionCheckAnswer,
    UdpAnswer,
    CreateUnit,
    CharacterPosition,
    CharacterAction,
}